# Generated by Django 2.2.4 on 2020-07-14 17:58

from django.db import migrations

def copy_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner_name,
            phonenumber=flat.owners_phonenumber,
            phone_pure=flat.owner_phone_pure
        )

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200714_2043'),
    ]

    operations = [
        migrations.RunPython(copy_flats_to_owners)
    ]
