# Generated by Django 2.2.4 on 2020-07-15 16:41

from django.db import migrations, models

def add_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get(
            name=flat.owner_name,
            phone_pure=flat.owner_phone_pure
        )
        owner.flats.add(flat)
        owner.save()

def success(apps, schema_editor):
    print("Success!")

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200715_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, db_index=True, to='property.Flat',
                                         verbose_name='Квартиры в собственности'),
        ),
        migrations.RunPython(
            success
        ),
        migrations.RunPython(
            add_flats_to_owners
        ),
        migrations.RunPython(
            success
        ),
    ]
