# Generated by Django 2.2.4 on 2020-07-21 17:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20200721_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
