# Generated by Django 2.2.4 on 2020-07-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20200721_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='phone_pure',
            new_name='pure_phonenumber',
        ),
    ]
